CREATE TABLE IF NOT EXISTS users ( id SERIAL PRIMARY KEY, email VARCHAR(255) UNIQUE NOT NULL, username VARCHAR(100) UNIQUE NOT NULL, full_name VARCHAR(255), hashed_password VARCHAR(255) NOT NULL, phone VARCHAR(20), city VARCHAR(100), region VARCHAR(100), address VARCHAR(255), date_of_birth VARCHAR(50), bio TEXT, company VARCHAR(255), license_number VARCHAR(100), experience VARCHAR(50), website VARCHAR(500), facebook VARCHAR(500), instagram VARCHAR(500), linkedin VARCHAR(500), email_notifications BOOLEAN DEFAULT TRUE, push_notifications BOOLEAN DEFAULT TRUE, profile_visibility VARCHAR(20) DEFAULT 'public', email_visibility VARCHAR(20) DEFAULT 'private', phone_visibility VARCHAR(20) DEFAULT 'private', seller_documents_submitted BOOLEAN DEFAULT FALSE, landlord_documents_submitted BOOLEAN DEFAULT FALSE, role_type VARCHAR(50) DEFAULT 'buyer', status VARCHAR(50) DEFAULT 'pending', is_active BOOLEAN DEFAULT TRUE, is_verified BOOLEAN DEFAULT FALSE, is_activated BOOLEAN DEFAULT FALSE, activation_request_id INTEGER, activated_at TIMESTAMP WITH TIME ZONE, has_active_subscription BOOLEAN DEFAULT FALSE, subscription_plan VARCHAR(50) DEFAULT 'free', subscription_start_date TIMESTAMP WITH TIME ZONE, subscription_end_date TIMESTAMP WITH TIME ZONE, payment_status VARCHAR(50) DEFAULT 'pending', payment_approved BOOLEAN DEFAULT FALSE, can_create_listings BOOLEAN DEFAULT FALSE, seller_enabled BOOLEAN DEFAULT FALSE, seller_approved BOOLEAN DEFAULT FALSE, seller_paid BOOLEAN DEFAULT FALSE, landlord_enabled BOOLEAN DEFAULT FALSE, landlord_approved BOOLEAN DEFAULT FALSE, landlord_paid BOOLEAN DEFAULT FALSE, avatar_url VARCHAR(500), created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(), updated_at TIMESTAMP WITH TIME ZONE, last_login TIMESTAMP WITH TIME ZONE ); 

-- Listings table: ensures auto-incrementing IDs and correct schema for property listings
CREATE TABLE IF NOT EXISTS listings (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price NUMERIC,
    listing_type VARCHAR(50) DEFAULT 'sale',
    property_type VARCHAR(50) DEFAULT 'house',
    bedrooms INTEGER DEFAULT 0,
    bathrooms INTEGER DEFAULT 0,
    sqft INTEGER DEFAULT 0,
    year_built INTEGER,
    status VARCHAR(50) DEFAULT 'draft',
    latitude NUMERIC,
    longitude NUMERIC,
    address TEXT,
    city VARCHAR(100),
    region VARCHAR(100),
    sub_city VARCHAR(100),
    kebele VARCHAR(100),
    zip_code VARCHAR(20),
    images TEXT,
    cover_image VARCHAR(500),
    videos TEXT,
    documents TEXT,
    amenities TEXT,
    phone_number VARCHAR(20),
    email VARCHAR(255),
    views_count INTEGER DEFAULT 0,
    featured BOOLEAN DEFAULT FALSE,
    is_draft BOOLEAN DEFAULT TRUE,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE,
    published_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_listings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
