import React, { createContext, useState, useContext, useEffect } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => useContext(LanguageContext)

const translations = {
  en: {
    // Common
    brand: 'RealEstate Pro',
    home: 'Home',
    properties: 'Properties',
    about: 'About',
    contact: 'Contact',
    pricing: 'Pricing',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    getStarted: 'Get Started',
    dashboard: 'Dashboard',
    logout: 'Logout',
    settings: 'Settings',
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    username: 'Username',
    phone: 'Phone',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    welcomeBack: 'Welcome Back',
    signInToAccount: 'Sign in to your account',
    createNewAccount: 'Create a new account',
    joinCommunity: 'Join our community',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    rememberMe: 'Remember Me',
    
    // Homepage
    heroTitle: 'Find Your Dream Property',
    heroSubtitle: 'Discover the best real estate opportunities in Ethiopia',
    searchPlaceholder: 'Search by city, region, or property type...',
    searchBtn: 'Search',
    featuredProperties: 'Featured Properties',
    whyChoose: 'Why Choose Us',
    trustedPlatform: 'Trusted Platform',
    verifiedProperties: 'Verified Properties',
    secureTransactions: 'Secure Transactions',
    bestDeals: 'Best Deals',
    footerDesc: 'Your trusted partner in real estate',
    quickLinks: 'Quick Links',
    contactUs: 'Contact Us',
    copyright: 'All rights reserved',
    propertiesForSale: 'For Sale',
    propertiesForRent: 'For Rent',
    viewDetails: 'View Details',
    learnMore: 'Learn More',
    
    // Create Listing
    createListing: 'Create Listing',
    addRentalProperty: 'Add Rental Property',
    editListing: 'Edit Listing',
    editProperty: 'Edit Property',
    propertyTitle: 'Property Title',
    propertyType: 'Property Type',
    price: 'Price',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    squareFeet: 'Square Feet',
    yearBuilt: 'Year Built',
    address: 'Address',
    city: 'City',
    region: 'Region',
    description: 'Description',
    photos: 'Photos',
    uploadPhotos: 'Click to upload photos',
    photoLimit: 'PNG, JPG up to 10MB',
    continueBtn: 'Continue',
    backBtn: 'Back',
    submitBtn: 'Submit',
    adding: 'Adding...',
    creating: 'Creating...',
    basicInfo: 'Basic Info',
    location: 'Location',
    amenitiesFeatures: 'Amenities & Features',
    photosDetails: 'Photos & Details',
    monthlyRent: 'Monthly Rent',
    furnishedStatus: 'Furnished Status',
    availableFrom: 'Available From',
    leaseTerm: 'Lease Term',
    securityDeposit: 'Security Deposit',
    
    // Property Types
    house: 'House',
    apartment: 'Apartment',
    villa: 'Villa',
    condo: 'Condo',
    land: 'Land',
    commercial: 'Commercial',
    townhouse: 'Townhouse',
    
    // Amenities
    amenities: 'Amenities',
    features: 'Features',
    wifi: 'WiFi',
    ac: 'Air Conditioning',
    heating: 'Heating',
    parking: 'Parking',
    pool: 'Swimming Pool',
    gym: 'Gym',
    security: 'Security System',
    garden: 'Garden',
    petFriendly: 'Pet Friendly',
    furnishedAmenity: 'Furnished',
    smartHome: 'Smart Home',
    
    // Messages
    listingCreated: 'Listing created successfully!',
    propertyAdded: 'Property added successfully!',
    fillRequired: 'Please fill all required fields',
    uploadPhoto: 'Please upload at least one photo',
    updateSuccess: 'Updated successfully!',
    deleteSuccess: 'Deleted successfully!',
    deleteConfirm: 'Are you sure you want to delete this?',
    
    // Dashboard
    totalProperties: 'Total Properties',
    activeListings: 'Active Listings',
    totalViews: 'Total Views',
    messages: 'Messages',
    rentalIncome: 'Rental Income',
    recentActivity: 'Recent Activity',
    recentListings: 'Recent Listings',
    noListings: 'No listings yet',
    createFirstListing: 'Create your first listing',
    myListings: 'My Listings',
    myProperties: 'My Properties',
    managePropertiesForSale: 'Manage your properties for sale',
    manageRentalProperties: 'Manage your rental properties',
    showing: 'Showing',
    of: 'of',
    propertiesFound: 'properties found',
    createNewListing: 'Create New Listing',
    addProperty: 'Add Property',
    noSaleListings: 'No sale listings yet',
    noRentalProperties: 'No rental properties yet',
    
    // Sidebar
    sellerAccount: 'SELLER ACCOUNT',
    landlordAccount: 'LANDLORD ACCOUNT',
    activity: 'ACTIVITY',
    savedSection: 'SAVED',
    management: 'MANAGEMENT',
    account: 'ACCOUNT',
    createListingMenu: 'Create Listing',
    myListingsMenu: 'My Listings',
    addRentalPropertyMenu: 'Add Rental Property',
    myPropertiesMenu: 'My Properties',
    notifications: 'Notifications',
    recent: 'Recent',
    saved: 'Saved',
    verification: 'Verification',
    subscription: 'Subscription',
    reviews: 'Reviews',
    
    // Admin Dashboard
    adminDashboard: 'Admin Dashboard',
    institutionalPortal: 'Institutional Real Estate Management Portal',
    userManagement: 'User Management',
    companyManagement: 'Company Management',
    listingsManagement: 'Listings Management',
    communications: 'Communications',
    subscriptionPayments: 'Subscription & Payments',
    complianceTrust: 'Compliance & Trust',
    systemSettings: 'System Settings',
    dashboardOverview: 'Dashboard Overview',
    totalUsers: 'Total Users',
    highPriority: 'High Priority',
    activeListingsAdmin: 'Active Listings',
    recentRevenue: 'Recent Revenue',
    pendingApproval: 'Pending Approval',
    platformStats: 'Platform Stats',
    companies: 'Companies',
    listings: 'Listings',
    portfolioValue: 'Portfolio Value',
    compliance: 'Compliance',
    manageUsers: 'Manage Users',
    addCompany: 'Add Company',
    companyName: 'Company Name',
    contactEmail: 'Contact Email',
    propertiesCount: 'Properties',
    actions: 'Actions',
    editUser: 'Edit User',
    suspendUser: 'Suspend User',
    approveSeller: 'Approve Seller',
    approveLandlord: 'Approve Landlord',
    userPermissions: 'User Permissions',
    canCreateListings: 'Can Create Listings',
    canAddProperties: 'Can Add Properties',
    canSendMessages: 'Can Send Messages',
    canViewReports: 'Can View Reports',
    canManageUsers: 'Can Manage Users',
    
    // Admin Settings
    generalSettings: 'General Settings',
    configurePlatform: 'Configure your platform settings',
    siteName: 'Site Name',
    adminEmail: 'Admin Email',
    supportEmail: 'Support Email',
    contactPhone: 'Contact Phone',
    emailConfiguration: 'Email Configuration',
    smtpHost: 'SMTP Host',
    smtpPort: 'SMTP Port',
    emailNotifications: 'Email Notifications',
    receiveSystemNotifications: 'Receive system notifications via email',
    securitySettings: 'Security Settings',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    twoFactorAuth: 'Two-Factor Authentication',
    addExtraSecurity: 'Add an extra layer of security to your account',
    regionalSettings: 'Regional Settings',
    language: 'Language',
    timezone: 'Timezone',
    currency: 'Currency',
    saveSettings: 'Save All Settings',
    reset: 'Reset',
    
    // Status Badges
    activeStatus: 'Active',
    pendingStatus: 'Pending',
    suspendedStatus: 'Suspended',
    verifiedStatus: 'Verified',
    notVerifiedStatus: 'Not Verified',
    forSaleBadge: 'For Sale',
    forRentBadge: 'For Rent',
    featuredBadge: 'Featured',
    
    // Filters
    filterProperties: 'Filter Properties',
    resetAll: 'Reset All',
    sortBy: 'Sort By',
    latest: 'Latest',
    oldest: 'Oldest',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    priceRange: 'Price Range',
    anyPrice: 'Any Price',
    anyBedrooms: 'Any',
    anyBathrooms: 'Any',
    allLocations: 'All Locations',
    gridView: 'Grid View',
    listView: 'List View',
    
    // Footer
    newsletter: 'Newsletter',
    subscribe: 'Subscribe',
    subscribeForUpdates: 'Subscribe for updates'
  },
  am: {
    // Common
    brand: 'ሪል እስቴት ፕሮ',
    home: 'መነሻ',
    properties: 'ንብረቶች',
    about: 'ስለ እኛ',
    contact: 'አግኙን',
    pricing: 'ዋጋ',
    signIn: 'ግባ',
    signUp: 'ተመዝገብ',
    getStarted: 'ይጀምሩ',
    dashboard: 'ዳሽቦርድ',
    logout: 'ውጣ',
    settings: 'ቅንብሮች',
    save: 'አስቀምጥ',
    cancel: 'ሰርዝ',
    loading: 'በመጫን ላይ...',
    email: 'ኢሜይል',
    password: 'የይለፍ ቃል',
    confirmPassword: 'የይለፍ ቃል አረጋግጥ',
    fullName: 'ሙሉ ስም',
    username: 'የተጠቃሚ ስም',
    phone: 'ስልክ ቁጥር',
    createAccount: 'አካውንት ፍጠር',
    alreadyHaveAccount: 'አካውንት አለዎት?',
    dontHaveAccount: 'አካውንት የለዎትም?',
    welcomeBack: 'እንኳን ደህና መጡ',
    signInToAccount: 'ወደ አካውንትዎ ይግቡ',
    createNewAccount: 'አዲስ አካውንት ይፍጠሩ',
    joinCommunity: 'ከማህበረሰባችን ጋር ይቀላቀሉ',
    forgotPassword: 'የይለፍ ቃል ረሳሁ?',
    resetPassword: 'የይለፍ ቃል ዳግም አስጀምር',
    sendResetLink: 'አገናኝ ላክ',
    backToLogin: 'ወደ ግቤት ተመለስ',
    rememberMe: 'አስታውሰኝ',
    
    // Homepage
    heroTitle: 'የህልምዎን ንብረት ያግኙ',
    heroSubtitle: 'በኢትዮጵያ ውስጥ ምርጥ የሪል እስቴት እድሎችን ያግኙ',
    searchPlaceholder: 'በከተማ፣ ክልል ወይም የንብረት አይነት ይፈልጉ...',
    searchBtn: 'ፈልግ',
    featuredProperties: 'ታዋቂ ንብረቶች',
    whyChoose: 'ለምን እኛን ይምረጡ',
    trustedPlatform: 'የታመነ መድረክ',
    verifiedProperties: 'የተረጋገጡ ንብረቶች',
    secureTransactions: 'ደህንነቱ የተጠበቀ ግብይት',
    bestDeals: 'ምርጥ ቅናሾች',
    footerDesc: 'በሪል እስቴት የታመነ አጋርዎ',
    quickLinks: 'ፈጣን አገናኞች',
    contactUs: 'አግኙን',
    copyright: 'ሁሉም መብቶች ተጠብቀዋል',
    propertiesForSale: 'ለሽያጭ',
    propertiesForRent: 'ለኪራይ',
    viewDetails: 'ዝርዝር ይመልከቱ',
    learnMore: 'ተጨማሪ ይወቁ',
    
    // Create Listing
    createListing: 'ንብረት ዝርዝር ፍጠር',
    addRentalProperty: 'የኪራይ ንብረት ጨምር',
    editListing: 'ዝርዝር አርትዕ',
    editProperty: 'ንብረት አርትዕ',
    propertyTitle: 'የንብረት ርዕስ',
    propertyType: 'የንብረት አይነት',
    price: 'ዋጋ',
    bedrooms: 'መኝታ ቤት',
    bathrooms: 'መታጠቢያ ቤት',
    squareFeet: 'ካሬ ጫማ',
    yearBuilt: 'የተሰራበት ዓመት',
    address: 'አድራሻ',
    city: 'ከተማ',
    region: 'ክልል',
    description: 'መግለጫ',
    photos: 'ፎቶዎች',
    uploadPhotos: 'ፎቶዎችን ለመስቀል ጠቅ ያድርጉ',
    photoLimit: 'PNG, JPG እስከ 10MB',
    continueBtn: 'ቀጥል',
    backBtn: 'ተመለስ',
    submitBtn: 'አስገባ',
    adding: 'በመጨመር ላይ...',
    creating: 'በመፍጠር ላይ...',
    basicInfo: 'መሰረታዊ መረጃ',
    location: 'አካባቢ',
    amenitiesFeatures: 'መገልገያዎች እና ባህሪያት',
    photosDetails: 'ፎቶዎች እና ዝርዝሮች',
    monthlyRent: 'ወርሃዊ ኪራይ',
    furnishedStatus: 'የቤት እቃ ሁኔታ',
    availableFrom: 'የሚገኝበት ቀን',
    leaseTerm: 'የውል ጊዜ',
    securityDeposit: 'የዋስትና ተቀማጭ',
    
    // Property Types
    house: 'ቤት',
    apartment: 'አፓርታማ',
    villa: 'ቪላ',
    condo: 'ኮንዶ',
    land: 'መሬት',
    commercial: 'የንግድ',
    townhouse: 'ታውን ሀውስ',
    
    // Amenities
    amenities: 'መገልገያዎች',
    features: 'ባህሪያት',
    wifi: 'ዋይፋይ',
    ac: 'ኤር ኮንዲሽነር',
    heating: 'ማሞቂያ',
    parking: 'መኪና ማቆሚያ',
    pool: 'መዋኛ ገንዳ',
    gym: 'ጂም',
    security: 'የደህንነት ሲስተም',
    garden: 'ጓሮ',
    petFriendly: 'የቤት እንስሳ ተቀባይ',
    furnishedAmenity: 'የተሟላ ቤት',
    smartHome: 'ስማርት ቤት',
    
    // Messages
    listingCreated: 'ዝርዝር በተሳካ ሁኔታ ተፈጥሯል!',
    propertyAdded: 'ንብረት በተሳካ ሁኔታ ተጨምሯል!',
    fillRequired: 'እባክዎ ሁሉንም አስፈላጊ መስኮች ይሙሉ',
    uploadPhoto: 'እባክዎ ቢያንስ አንድ ፎቶ ይስቀሉ',
    updateSuccess: 'በተሳካ ሁኔታ ተዘምኗል!',
    deleteSuccess: 'በተሳካ ሁኔታ ተሰርዟል!',
    deleteConfirm: 'ይህን መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት?',
    
    // Dashboard
    totalProperties: 'ጠቅላላ ንብረቶች',
    activeListings: 'ንቁ ዝርዝሮች',
    totalViews: 'ጠቅላላ እይታዎች',
    messages: 'መልዕክቶች',
    rentalIncome: 'የኪራይ ገቢ',
    recentActivity: 'የቅርብ ጊዜ እንቅስቃሴ',
    recentListings: 'የቅርብ ጊዜ ዝርዝሮች',
    noListings: 'እስካሁን ምንም ዝርዝሮች የሉም',
    createFirstListing: 'የመጀመሪያ ዝርዝርዎን ይፍጠሩ',
    myListings: 'የኔ ዝርዝሮች',
    myProperties: 'የኔ ንብረቶች',
    managePropertiesForSale: 'ለሽያጭ የሚቀርቡ ንብረቶችዎን ያስተዳድሩ',
    manageRentalProperties: 'የኪራይ ንብረቶችዎን ያስተዳድሩ',
    showing: 'እያሳየ',
    of: 'ከ',
    propertiesFound: 'ንብረቶች ተገኝተዋል',
    createNewListing: 'አዲስ ዝርዝር ፍጠር',
    addProperty: 'ንብረት ጨምር',
    noSaleListings: 'እስካሁን ምንም የሽያጭ ዝርዝሮች የሉም',
    noRentalProperties: 'እስካሁን ምንም የኪራይ ንብረቶች የሉም',
    
    // Sidebar
    sellerAccount: 'የሻጭ አካውንት',
    landlordAccount: 'የአከራይ አካውንት',
    activity: 'እንቅስቃሴ',
    savedSection: 'የተቀመጡ',
    management: 'አስተዳደር',
    account: 'አካውንት',
    createListingMenu: 'ዝርዝር ፍጠር',
    myListingsMenu: 'የኔ ዝርዝሮች',
    addRentalPropertyMenu: 'የኪራይ ንብረት ጨምር',
    myPropertiesMenu: 'የኔ ንብረቶች',
    notifications: 'ማስታወቂያዎች',
    recent: 'የቅርብ ጊዜ',
    saved: 'የተቀመጡ',
    verification: 'ማረጋገጫ',
    subscription: 'ደምዝገባ',
    reviews: 'ግምገማዎች',
    
    // Admin Dashboard
    adminDashboard: 'የአስተዳዳሪ ዳሽቦርድ',
    institutionalPortal: 'የተቋማት ሪል እስቴት ማኔጅመንት ፖርታል',
    userManagement: 'የተጠቃሚ አስተዳደር',
    companyManagement: 'የኩባንያ አስተዳደር',
    listingsManagement: 'የዝርዝሮች አስተዳደር',
    communications: 'ግንኙነቶች',
    subscriptionPayments: 'ደምዝገባ እና ክፍያዎች',
    complianceTrust: 'ተገዢነት እና እምነት',
    systemSettings: 'የስርዓት ቅንብሮች',
    dashboardOverview: 'ዳሽቦርድ አጠቃላይ እይታ',
    totalUsers: 'ጠቅላላ ተጠቃሚዎች',
    highPriority: 'ከፍተኛ ቅድሚያ',
    activeListingsAdmin: 'ንቁ ዝርዝሮች',
    recentRevenue: 'የቅርብ ጊዜ ገቢ',
    pendingApproval: 'በመጠባበቅ ላይ',
    platformStats: 'የመድረክ ስታቲስቲክስ',
    companies: 'ኩባንያዎች',
    listings: 'ዝርዝሮች',
    portfolioValue: 'የፖርትፎሊዮ ዋጋ',
    compliance: 'ተገዢነት',
    manageUsers: 'ተጠቃሚዎችን ያስተዳድሩ',
    addCompany: 'ኩባንያ ጨምር',
    companyName: 'የኩባንያ ስም',
    contactEmail: 'የእውቂያ ኢሜይል',
    propertiesCount: 'ንብረቶች',
    actions: 'ድርጊቶች',
    editUser: 'ተጠቃሚ አርትዕ',
    suspendUser: 'ተጠቃሚ እገዳ',
    approveSeller: 'ሻጭ አጽድቅ',
    approveLandlord: 'አከራይ አጽድቅ',
    userPermissions: 'የተጠቃሚ ፈቃዶች',
    canCreateListings: 'ዝርዝሮች መፍጠር ይችላል',
    canAddProperties: 'ንብረቶች መጨመር ይችላል',
    canSendMessages: 'መልዕክቶች መላክ ይችላል',
    canViewReports: 'ሪፖርቶች መመልከት ይችላል',
    canManageUsers: 'ተጠቃሚዎች ማስተዳደር ይችላል',
    
    // Admin Settings
    generalSettings: 'አጠቃላይ ቅንብሮች',
    configurePlatform: 'የመድረክ ቅንብሮችዎን ያዋቅሩ',
    siteName: 'የጣቢያ ስም',
    adminEmail: 'የአስተዳዳሪ ኢሜይል',
    supportEmail: 'የድጋፍ ኢሜይል',
    contactPhone: 'የእውቂያ ስልክ',
    emailConfiguration: 'የኢሜይል ውቅር',
    smtpHost: 'SMTP አስተናጋጅ',
    smtpPort: 'SMTP ወደብ',
    emailNotifications: 'የኢሜይል ማሳወቂያዎች',
    receiveSystemNotifications: 'የስርዓት ማሳወቂያዎችን በኢሜይል ይቀበሉ',
    securitySettings: 'የደህንነት ቅንብሮች',
    changePassword: 'የይለፍ ቃል ቀይር',
    currentPassword: 'አሁን ያለው የይለፍ ቃል',
    newPassword: 'አዲስ የይለፍ ቃል',
    confirmNewPassword: 'አዲስ የይለፍ ቃል አረጋግጥ',
    twoFactorAuth: 'ባለ ሁለት ደረጃ ማረጋገጫ',
    addExtraSecurity: 'ለአካውንትዎ ተጨማሪ የደህንነት ሽፋን ይጨምሩ',
    regionalSettings: 'ክልላዊ ቅንብሮች',
    language: 'ቋንቋ',
    timezone: 'የሰዓት ሰቅ',
    currency: 'ገንዘብ',
    saveSettings: 'ሁሉንም ቅንብሮች አስቀምጥ',
    reset: 'አስጀምር',
    
    // Status Badges
    activeStatus: 'ንቁ',
    pendingStatus: 'በመጠባበቅ ላይ',
    suspendedStatus: 'ታግዷል',
    verifiedStatus: 'ተረጋግጧል',
    notVerifiedStatus: 'አልተረጋገጠም',
    forSaleBadge: 'ለሽያጭ',
    forRentBadge: 'ለኪራይ',
    featuredBadge: 'ታዋቂ',
    
    // Filters
    filterProperties: 'ንብረቶችን አጣራ',
    resetAll: 'ሁሉንም አስጀምር',
    sortBy: 'አሰልድ በ',
    latest: 'አዲስ',
    oldest: 'አሮጌ',
    priceLowHigh: 'ዋጋ ከዝቅተኛ ወደ ከፍተኛ',
    priceHighLow: 'ዋጋ ከከፍተኛ ወደ ዝቅተኛ',
    priceRange: 'የዋጋ ክልል',
    anyPrice: 'ማንኛውም ዋጋ',
    anyBedrooms: 'ማንኛውም',
    anyBathrooms: 'ማንኛውም',
    allLocations: 'ሁሉም አካባቢዎች',
    gridView: 'ሰልፍ እይታ',
    listView: 'ዝርዝር እይታ',
    
    // Footer
    newsletter: 'ጋዜጣ',
    subscribe: 'ደንበኛ ይሁኑ',
    subscribeForUpdates: 'ለዝማኔዎች ደንበኛ ይሁኑ'
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en'
  })

  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])

  const t = (key) => {
    return translations[language][key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}