// src/context/LanguageContext.jsx
import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Complete translations for ENTIRE system
const translations = {
  en: {

    // ========== NAVIGATION ==========
    'home': 'Home',
    'properties': 'Properties',
    'about': 'About',
    'contact': 'Contact',
    'dashboard': 'Dashboard',
    'settings': 'Settings',
    'logout': 'Logout',
    'signin': 'Sign In',
    'signup': 'Sign Up',
    'language': 'Language',
    
    // ========== HERO SECTION ==========
    'find_dream_property': 'Find Your Dream Property',
    'discover_best_estate': 'Discover the best real estate opportunities in Ethiopia',
    'search_placeholder': 'Search by city, region, or property type...',
    'filters': 'Filters',
    'reset': 'Reset',
    'filter_properties': 'Filter Properties',
    'sort_by': 'Sort By',
    'latest': 'Latest',
    'price_low_high': 'Price: Low to High',
    'price_high_low': 'Price: High to Low',
    'price_range': 'Price Range',
    'any_price': 'Any Price',
    'any': 'Any',
    'location': 'Location',
    'all_locations': 'All Locations',
    'bedrooms': 'Bedrooms',
    'bathrooms': 'Bathrooms',
    'clear_filters': 'Clear Filters',
    'view_details': 'View Details',
    'see_more': 'See More Properties',
    'no_properties': 'No properties found',
    
    // ========== PROPERTY TABS ==========
    'all_properties': 'All Properties',
    'for_sale': 'For Sale',
    'for_rent': 'For Rent',
    'featured': 'Featured',
    
    // ========== PROPERTY DETAILS ==========
    'beds': 'beds',
    'baths': 'baths',
    'sqft': 'sqft',
    'price': 'Price',
    'description': 'Description',
    'amenities': 'Amenities',
    'location_map': 'Location on Map',
    'contact_owner': 'Contact Owner',
    'monthly_rent': 'Monthly rent',
    'full_address': 'Full Address',
    'address_not_available': 'Address not available',
    'go_home': 'Go Home',
    'similar_properties': 'Similar Properties',
    'property_details': 'Property Details',
    'property_type': 'Property Type',
    'year_built': 'Year Built',
    'listing_date': 'Listing Date',
    
    // ========== DASHBOARD COMMON ==========
    'welcome_back': 'Welcome back',
    'total_listings': 'Total Listings',
    'active_properties': 'Active Properties',
    'total_views': 'Total Views',
    'rental_units': 'Rental Units',
    'quick_actions': 'Quick Actions',
    'create_listing': 'Create Listing',
    'my_listings': 'My Listings',
    'messages': 'Messages',
    'activation': 'Activation',
    'subscription': 'Subscription',
    'statistics': 'Statistics',
    'recent_activity': 'Recent Activity',
    
    // ========== SELLER DASHBOARD ==========
    'seller_dashboard': 'Seller Dashboard',
    'manage_listings': 'Manage Listings',
    'add_new_listing': 'Add New Listing',
    'edit_listing': 'Edit Listing',
    'delete_listing': 'Delete Listing',
    'listing_status': 'Listing Status',
    'views_count': 'Views',
    'inquiries': 'Inquiries',
    
    // ========== BUYER DASHBOARD ==========
    'buyer_dashboard': 'Buyer Dashboard',
    'browse_properties': 'Browse Properties',
    'saved_properties': 'Saved Properties',
    'start_exploring': 'Start Exploring',
    'your_favorites': 'Your Favorites',
    'chat_property_owners': 'Chat with property owners',
    'find_dream_home': 'Find your dream home',
    'start_conversation': 'Start a conversation',
    
    // ========== ADMIN DASHBOARD ==========
    'admin_panel': 'Admin Panel',
    'user_management': 'User Management',
    'verification_queue': 'Verification Queue',
    'payment_approvals': 'Payment Approvals',
    'reports_analytics': 'Reports & Analytics',
    'admin_messages': 'Admin Messages',
    'company_settings': 'Company Settings',
    'admin_settings': 'Admin Settings',
    'total_users': 'Total Users',
    'total_revenue': 'Total Revenue',
    'pending_payments': 'Pending Payments',
    
    // ========== ACTIVATION & SUBSCRIPTION ==========
    'account_activation': 'Account Activation',
    'submit_documents': 'Submit Documents',
    'upload_documents': 'Upload Documents',
    'documents_under_review': 'Documents Under Review',
    'documents_approved': 'Documents Approved!',
    'payment_pending': 'Payment Pending',
    'subscribe_now': 'Subscribe Now',
    'choose_plan': 'Choose Your Plan',
    'seller_plan': 'Seller Plan',
    'landlord_plan': 'Landlord Plan',
    'dual_plan': 'Dual Plan',
    'price_per_month': 'per month',
    'start_subscription': 'Start Subscription',
    
    // ========== SETTINGS ==========
    'profile_information': 'Profile Information',
    'update_personal_details': 'Update your personal details and public profile',
    'security': 'Security',
    'manage_account_security': 'Manage your account security',
    'notification_preferences': 'Notification Preferences',
    'choose_notification': 'Choose how you want to be notified',
    'email_alerts': 'Email Alerts',
    'receive_important_alerts': 'Receive important alerts via email',
    'new_user_notifications': 'New User Notifications',
    'get_notified_new_users': 'Get notified when new users register',
    'payment_notifications': 'Payment Notifications',
    'get_notified_payments': 'Get notified about new payments',
    'appearance': 'Appearance',
    'customize_platform_look': 'Customize how the platform looks',
    'theme_preference': 'Theme Preference',
    'light_mode': 'Light Mode',
    'dark_mode': 'Dark Mode',
    'save_changes': 'Save Changes',
    'change_password': 'Change Password',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_password': 'Confirm Password',
    'passwords_match': 'Passwords match!',
    'passwords_do_not_match': 'Passwords do not match',
    'password_min_length': 'Password must be at least 6 characters',
    'remove_photo': 'Remove photo',
    'upload_photo': 'Upload photo',
    
    // ========== PROFILE FORM ==========
    'full_name': 'Full Name',
    'email_address': 'Email Address',
    'phone_number': 'Phone Number',
    'username': 'Username',
    'position': 'Position',
    'department': 'Department',
    'date_of_birth': 'Date of Birth',
    'city_region': 'City / Region',
    'bio_about': 'Bio / About Me',
    'tell_about_yourself': 'Tell us about yourself...',
    'characters': 'characters',
    
    // ========== COMPANY SETTINGS ==========
    'company_information': 'Company Information',
    'update_company_details': 'Update your company details',
    'company_name': 'Company Name',
    'company_email': 'Company Email',
    'company_phone': 'Company Phone',
    'company_tin': 'Company TIN',
    'company_address': 'Company Address',
    'website': 'Website',
    'currency': 'Currency',
    'financial_settings': 'Financial Settings',
    'configure_fees_rates': 'Configure fees and rates',
    'tax_rate': 'Tax Rate (%)',
    'commission_rate': 'Commission Rate (%)',
    'listing_fee': 'Listing Fee (ETB)',
    'subscription_fees': 'Subscription Fees (Monthly)',
    'seller_plan_text': 'Seller Plan',
    'landlord_plan_text': 'Landlord Plan',
    'dual_plan_text': 'Dual Plan',
    'platform_statistics': 'Platform Statistics',
    'overview_performance': 'Overview of platform performance',
    'total_users_stat': 'Total Users',
    'total_listings_stat': 'Total Listings',
    'total_revenue_stat': 'Total Revenue',
    'refresh_stats': 'Refresh Stats',
    
    // ========== PAYMENT ==========
    'payment_approvals_title': 'Payment Approvals',
    'review_approve_payments': 'Review and approve subscription payments',
    'pending': 'Pending',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'all': 'All',
    'payment_details': 'Payment Details',
    'user_information': 'User Information',
    'payment_information': 'Payment Information',
    'payment_receipt': 'Payment Receipt',
    'print_receipt': 'Print Receipt',
    'approve_payment': 'Approve Payment',
    'reject_payment': 'Reject Payment',
    'rejection_reason': 'Rejection Reason',
    'please_provide_reason': 'Please provide a reason for rejection',
    'confirm_reject': 'Confirm Reject',
    'no_pending_payments': 'No Pending Payments',
    'all_payments_processed': 'All payment requests have been processed!',
    'payment_approved_success': '✅ Payment approved! Account activated.',
    'payment_rejected_success': '❌ Payment rejected',
    'receipt_ready': 'Receipt ready',
    'check_your_email': 'Check Your Email',
    'reset_code_sent_to': "We've sent a password reset code to",
    'reset_code_expires': 'The code will expire in 10 minutes.',
    'back_to_login': 'Back to Login',
    
    // ========== VERIFICATION QUEUE ==========
    'verification_queue_title': 'Verification Queue',
    'pending_verifications': 'Pending Verifications',
    'review_documents': 'Review Documents',
    'approve_documents': 'Approve Documents',
    'reject_documents': 'Reject Documents',
    'documents_pending': 'Documents Pending',
    'documents_submitted': 'Documents Submitted',
    'verify_user': 'Verify User',
    'user_details': 'User Details',
    'submitted_documents': 'Submitted Documents',
    'approval_status': 'Approval Status',
    
    // ========== MESSAGES ==========
    'messages_title': 'Messages',
    'no_messages': 'No messages yet',
    'start_conversation_title': 'Start a conversation',
    'type_message': 'Type your message...',
    'send': 'Send',
    'conversations': 'Conversations',
    'search_conversations': 'Search conversations...',
    'unread': 'Unread',
    'read': 'Read',
    'replied': 'Replied',
    
    // ========== FOOTER ==========
    'quick_links': 'Quick Links',
    'sell_property': 'Sell Property',
    'rent_property': 'Rent Property',
    'contact_us': 'Contact Us',
    'follow_us': 'Follow Us',
    'all_rights_reserved': 'All rights reserved.',
    'privacy_policy': 'Privacy Policy',
    'terms_service': 'Terms of Service',
    'newsletter': 'Newsletter',
    'subscribe_updates': 'Subscribe for updates',
    'your_email_placeholder': 'Your email',
    'subscribe': 'Subscribe',
    
    // ========== STATUS MESSAGES ==========
    'active': 'Active',
    'inactive': 'Inactive',
    'pending_approval': 'Pending Approval',
    'suspended': 'Suspended',
    'verified': 'Verified',
    'unverified': 'Unverified',
    
    // ========== BUTTONS ==========
    'update': 'Update',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'close': 'Close',
    'back': 'Back',
    'next': 'Next',
    'continue': 'Continue',
    'submit': 'Submit',
    'search': 'Search',
    'filter': 'Filter',
    'clear': 'Clear',
    'refresh': 'Refresh',
    'cancel': 'Cancel',
    'save': 'Save',
    'confirm': 'Confirm',
    
    // ========== ERROR & LOADING ==========
    'loading': 'Loading...',
    'error_occurred': 'An error occurred',
    'login_failed': 'Login failed. Please try again.',
    'cannot_connect_server': 'Cannot connect to server. Please make sure the backend is running on port 8000.',
    'google_auth_failed': 'Google authentication failed. Please try again.',
    'password_label': 'Password',
    'enter_your_password_label': 'Enter your password',
    'try_again': 'Try Again',
    'network_error': 'Network error. Please try again.',
    'session_expired': 'Session expired. Please login again.',
    'unauthorized': 'Unauthorized access',
    'forbidden': 'Access forbidden',
    'not_found': 'Page not found',
    
    // ========== SUCCESS MESSAGES ==========
    'profile_saved': 'Profile saved successfully!',
    'settings_saved': 'Settings saved successfully!',
    'password_changed': 'Password changed successfully!',
    'documents_uploaded': 'Documents uploaded successfully!',
    'payment_submitted': 'Payment submitted for verification!',
    'no_image': 'No image available',
    'call': 'Call',
    'send_email': 'Send Email',
    'contact_information': 'Contact Information',
    'show_less': 'Show less',
    'read_more': 'Read more',
    'opening_chat': 'Opening chat...',
    'message_owner_info': 'Message the owner directly through our secure chat',
    'saved_to_favorites': 'Saved to favorites',
    'removed_from_saved': 'Removed from saved',
    'link_copied': 'Link copied!',
    'home_hero_title': 'Find Your Dream Property',
    'home_hero_subtitle': 'Discover the best real estate opportunities in Ethiopia',
    'all_filters_reset': 'All filters reset',
    'see_more_properties': 'See More Properties',
    'no_properties_found': 'No properties found',
    'load_more': 'Loading more...',
    'back_to_home': 'Back to Home',
    'sign_in_to_account': 'Sign in to your account',
    'sign_in_to_explore_properties': 'Sign in to explore properties',
    'not_buyer_account': 'This account is not a buyer account.',
    'invalid_credentials': 'Invalid username or password',
    'email_or_username': 'Email or Username',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot Password?',
    'continue_with_google': 'Continue with Google',
    'dont_have_account': 'Don\'t have an account?',
    'already_have_account': 'Already have an account?',
    'create_account': 'Create Account',
    'create_seller_account': 'Create Seller Account',
    'create_account_subtitle': 'Create your account to start exploring properties',
    'seller_account_created': 'Seller account created successfully! Please login.',
    'registration_failed': 'Registration failed',
    'please_fill_required_fields': 'Please fill all required fields',
    'message_sent_success': 'Message sent successfully! We\'ll get back to you soon.',
    'visit_us': 'Visit Us',
    'call_us': 'Call Us',
    'email_us': 'Email Us',
    'business_hours': 'Business Hours',
    'send_us_message': 'Send Us a Message',
    'subject': 'Subject',
    'message': 'Message',
    'about_page_title': 'About RealEstate Pro',
    'about_page_subtitle': 'Ethiopia\'s most trusted real estate platform, connecting buyers, sellers, and renters since 2015',
    'our_story': 'Our Story',
    'our_core_values': 'Our Core Values',
    'our_mission': 'Our Mission',
    'our_vision': 'Our Vision',
    'our_mission_text': 'To simplify real estate transactions in Ethiopia by providing a transparent, efficient, and trustworthy platform that connects property seekers with their dream properties and property owners with the right buyers or tenants.',
    'our_vision_text': 'To become Ethiopia\'s most innovative and trusted real estate ecosystem, empowering individuals and businesses to make confident property decisions through technology, expertise, and exceptional service.',
    'trust_transparency': 'Trust & Transparency',
    'trust_transparency_text': 'We believe in complete transparency in all our dealings, ensuring our clients have all the information they need to make informed decisions.',
    'customer_first': 'Customer First',
    'customer_first_text': 'Our clients are at the heart of everything we do. We go above and beyond to ensure their satisfaction and success.',
    'excellence': 'Excellence',
    'excellence_text': 'We strive for excellence in every aspect of our service, from property listings to customer support.',
    'global_standards': 'Global Standards',
    'global_standards_text': 'We maintain international standards while understanding local Ethiopian market dynamics.',
    'properties_found': '{count} properties available',
    'property_type_label': 'Property Type',
    'all_cities': 'All Cities',
    'loading_more': 'Loading more...',
    'property_not_found': 'Property not found',
    'failed_to_load_property': 'Failed to load property',
    'contact_property_owner': 'Contact Property Owner',
    'create_buyer_account': 'Create Buyer Account',
    'login_to_buyer_account': 'Login to Buyer Account',
    'please_create_buyer_account': 'Please create a buyer account to contact the owner',
    'amenities_features': 'Amenities & Features',
    'open_chat': 'Opening chat...',
  },
  am: {
    // ========== ዳሰሳ ==========
    'home': 'መነሻ',
    'properties': 'ንብረቶች',
    'about': 'ስለእኛ',
    'contact': 'አግኙን',
    'dashboard': 'ዳሽቦርድ',
    'settings': 'ቅንብሮች',
    'logout': 'ውጣ',
    'signin': 'ግባ',
    'signup': 'ተመዝገብ',
    'language': 'ቋንቋ',
    
    // ========== ዋና ማስታወቂያ ==========
    'find_dream_property': 'ህልምዎን ንብረት ያግኙ',
    'discover_best_estate': 'በኢትዮጵያ ውስጥ ምርጥ የሪል እስቴት እድሎችን ይወቁ',
    'search_placeholder': 'በከተማ፣ በክልል ወይም በንብረት አይነት ይፈልጉ...',
    'filters': 'ማጣሪያዎች',
    'reset': 'ዳግም አስጀምር',
    'filter_properties': 'ንብረቶችን አጣራ',
    'sort_by': 'ደርድር በ',
    'latest': 'አዲስ',
    'price_low_high': 'ዋጋ፡ ከዝቅተኛ ወደ ከፍተኛ',
    'price_high_low': 'ዋጋ፡ ከከፍተኛ ወደ ዝቅተኛ',
    'price_range': 'የዋጋ ክልል',
    'any_price': 'ማንኛውም ዋጋ',
    'any': 'ማንኛውም',
    'location': 'አካባቢ',
    'all_locations': 'ሁሉም አካባቢዎች',
    'bedrooms': 'መኝታ ቤቶች',
    'bathrooms': 'መታጠቢያ ቤቶች',
    'clear_filters': 'ማጣሪያዎችን አጽዳ',
    'view_details': 'ዝርዝር ለማየት',
    'see_more': 'ተጨማሪ ንብረቶችን ይመልከቱ',
    'no_properties': 'ምንም ንብረቶች አልተገኙም',
    
    // ========== የንብረት ትሮች ==========
    'all_properties': 'ሁሉም ንብረቶች',
    'for_sale': 'ለሽያጭ',
    'for_rent': 'ለኪራይ',
    'featured': 'ታዋቂ',
    
    // ========== የንብረት ዝርዝሮች ==========
    'beds': 'መኝታ',
    'baths': 'መታጠቢያ',
    'sqft': 'ካሬ ጫማ',
    'price': 'ዋጋ',
    'description': 'መግለጫ',
    'amenities': 'መገልገያዎች',
    'location_map': 'በካርታ ላይ ያለው ቦታ',
    'contact_owner': 'ባለቤቱን ያግኙ',
    'monthly_rent': 'የወርኃዊ ኪራይ',
    'full_address': 'ሙሉ አድራሻ',
    'address_not_available': 'አድራሻ አልተገኘም',
    'go_home': 'ወደ መነሻ ተመለስ',
    'similar_properties': 'ተመሳሳይ ንብረቶች',
    'property_details': 'የንብረት ዝርዝሮች',
    'property_type': 'የንብረት አይነት',
    'year_built': 'የተሰራበት ዓመት',
    'listing_date': 'የዝርዝር ቀን',
    
    // ========== ዳሽቦርድ ==========
    'welcome_back': 'እንኳን ደህና መጡ',
    'total_listings': 'ጠቅላላ ዝርዝሮች',
    'active_properties': 'ንቁ ንብረቶች',
    'total_views': 'ጠቅላላ እይታዎች',
    'rental_units': 'የኪራይ ክፍሎች',
    'quick_actions': 'ፈጣን እርምጃዎች',
    'create_listing': 'አዲስ ዝርዝር ፍጠር',
    'my_listings': 'የኔ ዝርዝሮች',
    'messages': 'መልዕክቶች',
    'activation': 'ማግበር',
    'subscription': 'ምዝገባ',
    'statistics': 'ስታቲስቲክስ',
    'recent_activity': 'የቅርብ ጊዜ እንቅስቃሴ',
    
    // ========== ሻጭ ዳሽቦርድ ==========
    'seller_dashboard': 'የሻጭ ዳሽቦርድ',
    'manage_listings': 'ዝርዝሮችን ያስተዳድሩ',
    'add_new_listing': 'አዲስ ዝርዝር ያክሉ',
    'edit_listing': 'ዝርዝር ያርትዑ',
    'delete_listing': 'ዝርዝር ይሰርዙ',
    'listing_status': 'የዝርዝር ሁኔታ',
    'views_count': 'እይታዎች',
    'inquiries': 'ጥያቄዎች',
    
    // ========== ገዢ ዳሽቦርድ ==========
    'buyer_dashboard': 'የገዢ ዳሽቦርድ',
    'browse_properties': 'ንብረቶችን ያስሱ',
    'saved_properties': 'የተቀመጡ ንብረቶች',
    'start_exploring': 'መፈለግ ጀምር',
    'your_favorites': 'የሚወዷቸው',
    'chat_property_owners': 'ከንብረት ባለቤቶች ጋር ይወያዩ',
    'find_dream_home': 'ህልምዎን ቤት ያግኙ',
    'start_conversation': 'ውይይት ጀምር',
    
    // ========== አስተዳዳሪ ዳሽቦርድ ==========
    'admin_panel': 'የአስተዳዳሪ ፓነል',
    'user_management': 'የተጠቃሚ አስተዳደር',
    'verification_queue': 'የማረጋገጫ ወረፋ',
    'payment_approvals': 'የክፍያ ማጽደቂያዎች',
    'reports_analytics': 'ሪፖርቶች እና ትንታኔዎች',
    'admin_messages': 'የአስተዳዳሪ መልዕክቶች',
    'company_settings': 'የኩባንያ ቅንብሮች',
    'admin_settings': 'የአስተዳዳሪ ቅንብሮች',
    'total_users': 'ጠቅላላ ተጠቃሚዎች',
    'total_revenue': 'ጠቅላላ ገቢ',
    'pending_payments': 'በመጠበቅ ላይ ያሉ ክፍያዎች',
    
    // ========== ማግበሪያ እና ምዝገባ ==========
    'account_activation': 'የመለያ ማግበሪያ',
    'submit_documents': 'ሰነዶችን ያስገቡ',
    'upload_documents': 'ሰነዶችን ይጫኑ',
    'documents_under_review': 'ሰነዶች በግምገማ ላይ',
    'documents_approved': 'ሰነዶች ጸድቀዋል!',
    'payment_pending': 'ክፍያ በመጠበቅ ላይ',
    'subscribe_now': 'አሁን ይመዝገቡ',
    'choose_plan': 'እቅድዎን ይምረጡ',
    'seller_plan': 'የሻጭ እቅድ',
    'landlord_plan': 'የአከራይ እቅድ',
    'dual_plan': 'ድርብ እቅድ',
    'price_per_month': 'በወር',
    'start_subscription': 'ምዝገባ ጀምር',
    
    // ========== ቅንብሮች ==========
    'profile_information': 'የመገለጫ መረጃ',
    'update_personal_details': 'የግል ዝርዝሮችዎን ያዘምኑ',
    'security': 'ደህንነት',
    'manage_account_security': 'የመለያ ደህንነትዎን ያስተዳድሩ',
    'notification_preferences': 'የማሳወቂያ ምርጫዎች',
    'choose_notification': 'እንዴት መረጃ እንዲደርስዎ ይምረጡ',
    'email_alerts': 'የኢሜይል ማንቂያዎች',
    'receive_important_alerts': 'አስፈላጊ ማንቂያዎችን በኢሜይል ይቀበሉ',
    'new_user_notifications': 'አዲስ ተጠቃሚ ማሳወቂያዎች',
    'get_notified_new_users': 'አዲስ ተጠቃሚዎች ሲመዘገቡ ይረዱ',
    'payment_notifications': 'የክፍያ ማሳወቂያዎች',
    'get_notified_payments': 'ስለ አዳዲስ ክፍያዎች ይረዱ',
    'appearance': 'መልክ',
    'customize_platform_look': 'የመድረኩን ገጽታ ያብጁ',
    'theme_preference': 'የገጽታ ምርጫ',
    'light_mode': 'ቀላል ሁነታ',
    'dark_mode': 'ጨለማ ሁነታ',
    'save_changes': 'ለውጦችን አስቀምጥ',
    'change_password': 'የይለፍ ቃል ቀይር',
    'current_password': 'አሁን ያለው የይለፍ ቃል',
    'new_password': 'አዲስ የይለፍ ቃል',
    'confirm_password': 'የይለፍ ቃል አረጋግጥ',
    'passwords_match': 'የይለፍ ቃሎች ተመሳሳይ ናቸው!',
    'passwords_do_not_match': 'የይለፍ ቃሎች አይመሳሰሉም',
    'password_min_length': 'የይለፍ ቃል ቢያንስ 6 ቁምፊዎች መሆን አለበት',
    'remove_photo': 'ፎቶ አስወግድ',
    'upload_photo': 'ፎቶ ጫን',
    
    // ========== የመገለጫ ቅጽ ==========
    'full_name': 'ሙሉ ስም',
    'email_address': 'ኢሜይል አድራሻ',
    'phone_number': 'ስልክ ቁጥር',
    'username': 'የተጠቃሚ ስም',
    'position': 'እንቅስቃሴ',
    'department': 'ክፍል',
    'date_of_birth': 'የልደት ቀን',
    'city_region': 'ከተማ / ክልል',
    'bio_about': 'ስለእኔ',
    'tell_about_yourself': 'ስለራስዎ ይንገሩን...',
    'characters': 'ቁምፊዎች',
    
    // ========== የኩባንያ ቅንብሮች ==========
    'company_information': 'የኩባንያ መረጃ',
    'update_company_details': 'የኩባንያዎን ዝርዝሮች ያዘምኑ',
    'company_name': 'የኩባንያ ስም',
    'company_email': 'የኩባንያ ኢሜይል',
    'company_phone': 'የኩባንያ ስልክ',
    'company_tin': 'የኩባንያ ቲን',
    'company_address': 'የኩባንያ አድራሻ',
    'website': 'ድህረ ገጽ',
    'currency': 'ገንዘብ',
    'financial_settings': 'የፋይናንስ ቅንብሮች',
    'configure_fees_rates': 'ክፍያዎችን እና ተመኖችን ያዋቅሩ',
    'tax_rate': 'የግብር መጠን (%)',
    'commission_rate': 'ኮሚሽን መጠን (%)',
    'listing_fee': 'የዝርዝር ክፍያ (ብር)',
    'subscription_fees': 'የምዝገባ ክፍያዎች (በወር)',
    'seller_plan_text': 'የሻጭ እቅድ',
    'landlord_plan_text': 'የአከራይ እቅድ',
    'dual_plan_text': 'ድርብ እቅድ',
    'platform_statistics': 'የመድረክ ስታቲስቲክስ',
    'overview_performance': 'የመድረክ አፈጻጸም አጠቃላይ እይታ',
    'total_users_stat': 'ጠቅላላ ተጠቃሚዎች',
    'total_listings_stat': 'ጠቅላላ ዝርዝሮች',
    'total_revenue_stat': 'ጠቅላላ ገቢ',
    'refresh_stats': 'ስታቲስቲክስ አድስ',
    
    // ========== ክፍያ ==========
    'payment_approvals_title': 'የክፍያ ማጽደቂያዎች',
    'review_approve_payments': 'የምዝገባ ክፍያዎችን ይገምግሙ እና ያጽድቁ',
    'pending': 'በመጠበቅ ላይ',
    'approved': 'ጸድቋል',
    'rejected': 'ውድቅ ተደርጓል',
    'all': 'ሁሉም',
    'payment_details': 'የክፍያ ዝርዝሮች',
    'user_information': 'የተጠቃሚ መረጃ',
    'payment_information': 'የክፍያ መረጃ',
    'payment_receipt': 'የክፍያ ደረሰኝ',
    'print_receipt': 'ደረሰኝ አትም',
    'approve_payment': 'ክፍያ አጽድቅ',
    'reject_payment': 'ክፍያ ውድቅ አድርግ',
    'rejection_reason': 'የውድቀት ምክንያት',
    'please_provide_reason': 'እባክዎ ለውድቀቱ ምክንያት ይስጡ',
    'confirm_reject': 'ውድቅ ማድረግ አረጋግጥ',
    'no_pending_payments': 'በመጠበቅ ላይ ያለ ክፍያ የለም',
    'all_payments_processed': 'ሁሉም የክፍያ ጥያቄዎች ተከናውነዋል!',
    'payment_approved_success': '✅ ክፍያ ጸድቋል! መለያ ነቅቷል።',
    'payment_rejected_success': '❌ ክፍያ ውድቅ ተደርጓል',
    'receipt_ready': 'ደረሰኝ ዝግጁ ነው',
    'check_your_email': 'ኢሜልዎን ይፈትሩ',
    'reset_code_sent_to': 'የይለፍ ቃል ኮድ ወደ ኢሜይልዎ ተልኳል',
    'reset_code_expires': 'ኮድው ከ10 ደቂቃ በኋላ ይሰረዝላል።',
    'back_to_login': 'ወደ መግቢያ ተመለስ',
    
    // ========== የማረጋገጫ ወረፋ ==========
    'verification_queue_title': 'የማረጋገጫ ወረፋ',
    'pending_verifications': 'በመጠበቅ ላይ ያሉ ማረጋገጫዎች',
    'review_documents': 'ሰነዶችን ገምግም',
    'approve_documents': 'ሰነዶችን አጽድቅ',
    'reject_documents': 'ሰነዶችን ውድቅ አድርግ',
    'documents_pending': 'ሰነዶች በመጠበቅ ላይ',
    'documents_submitted': 'ሰነዶች ቀርበዋል',
    'verify_user': 'ተጠቃሚ አረጋግጥ',
    'user_details': 'የተጠቃሚ ዝርዝሮች',
    'submitted_documents': 'የቀረቡ ሰነዶች',
    'approval_status': 'የማጽደቅ ሁኔታ',
    
    // ========== መልዕክቶች ==========
    'messages_title': 'መልዕክቶች',
    'no_messages': 'እስካሁን ምንም መልዕክቶች የሉም',
    'start_conversation_title': 'ውይይት ጀምር',
    'type_message': 'መልዕክትዎን ይተይቡ...',
    'send': 'ላክ',
    'conversations': 'ውይይቶች',
    'search_conversations': 'ውይይቶችን ፈልግ...',
    'unread': 'ያልተነበበ',
    'read': 'ተነብቧል',
    'replied': 'መልስ ተሰጥቷል',
    
    // ========== ግርጌ ==========
    'quick_links': 'ፈጣን አገናኞች',
    'sell_property': 'ንብረት ሽጥ',
    'rent_property': 'ንብረት ኪራይ',
    'contact_us': 'አግኙን',
    'follow_us': 'ተከተሉን',
    'all_rights_reserved': 'ሁሉም መብቶች የተጠበቁ ናቸው።',
    'privacy_policy': 'የግላዊነት ፖሊሲ',
    'terms_service': 'የአገልግሎት ውሎች',
    'newsletter': 'ጋዜጣ',
    'subscribe_updates': 'ለዝማኔዎች ይመዝገቡ',
    'your_email_placeholder': 'ኢሜይልዎ',
    'subscribe': 'ይመዝገቡ',
    
    // ========== ሁኔታ ==========
    'active': 'ንቁ',
    'inactive': 'ንቁ ያልሆነ',
    'pending_approval': 'ማጽደቅ በመጠበቅ ላይ',
    'suspended': 'ታግዷል',
    'verified': 'ተረጋግጧል',
    'unverified': 'አልተረጋገጠም',
    
    // ========== ቁልፎች ==========
    'update': 'አዘምን',
    'delete': 'ሰርዝ',
    'edit': 'አርትዕ',
    'add': 'ጨምር',
    'close': 'ዝጋ',
    'back': 'ተመለስ',
    'next': 'ቀጥል',
    'continue': 'ቀጥል',
    'submit': 'አስገባ',
    'search': 'ፈልግ',
    'filter': 'አጣራ',
    'clear': 'አጽዳ',
    'refresh': 'አድስ',
    'cancel': 'ሰርዝ',
    'save': 'አስቀምጥ',
    'confirm': 'አረጋግጥ',
    
    // ========== ስህተት እና መጫን ==========
    'loading': 'በመጫን ላይ...',
    'error_occurred': 'ስህተት ተከስቷል',
    'login_failed_am': 'መግቢያ ጉድለት። እባክዎ ደግመው ይሞክሩ።',
    'cannot_connect_server_am': 'ከሰርቨሩ ጋር መገናኘት አልተቻለም። እባክዎ በ8000 ፖርት የታቀደው ተቋም እንዳለው ያረጋግጡ።',
    'google_auth_failed_am': 'የGoogle ማረጋገጫ አልተፈጸም። እባክዎ ደግመው ይሞክሩ።',
    'password_label_am': 'የይለፍ ቃል',
    'enter_your_password_label_am': 'የይለፍ ቃልዎን ያስገቡ',
    'try_again': 'እንደገና ይሞክሩ',
    'network_error': 'የኔትዎርክ ስህተት። እባክዎ እንደገና ይሞክሩ።',
    'session_expired': 'ክፍለ ጊዜ አልቋል። እባክዎ እንደገና ይግቡ።',
    'unauthorized': 'ያልተፈቀደ መዳረሻ',
    'forbidden': 'መዳረሻ የተከለከለ ነው',
    'not_found': 'ገጽ አልተገኘም',
    
    // ========== የስኬት መልዕክቶች ==========
    'profile_saved': 'መገለጫ በሚገባ ተቀምጧል!',
    'settings_saved': 'ቅንብሮች በሚገባ ተቀምጠዋል!',
    'password_changed': 'የይለፍ ቃል በሚገባ ተቀይሯል!',
    'documents_uploaded': 'ሰነዶች በሚገባ ተጭነዋል!',
    'payment_submitted': 'ክፍያ ለማረጋገጫ ቀርቧል!',
    'no_image': 'ምንም ምስል የለም',
    'call': 'ይደውሉ',
    'send_email': 'ኢሜይል ላክ',
    'contact_information': 'የአግኙ መረጃ',
    'show_less': 'ትንሽ አሳይ',
    'read_more': 'ተጨማሪ እይ',
    'opening_chat': 'ንግግር እየተከፈተ ነው...',
    'message_owner_info': 'ባለቤቱን በደህንነት የሚሰራ ቻት እንዲያግኙ ይላኩ',
    'saved_to_favorites': 'ወደ ተወዳጅ ተቀዝቷል',
    'removed_from_saved': 'ከተቀመጡ ውስጥ ወደ ውጭ ተወግዷል',
    'link_copied': 'አገናኝ ተቀባ!',
    'home_hero_title': 'ህልምዎን የሚያገኙ ንብረት ይፈልጉ',
    'home_hero_subtitle': 'በኢትዮጵያ ውስጥ ቅርጸ ቤት ዕድሎችን ይገናኙ',
    'all_filters_reset': 'ሁሉም ማጣሪያዎች ተደጋግሟል',
    'see_more_properties': 'ተጨማሪ ንብረቶችን ይመልከቱ',
    'no_properties_found': 'ምንም ንብረቶች አልተገኙም',
    'load_more': 'ተጨማሪ እይ',
    'back_to_home': 'ወደ መነሻ ተመለስ',
    'sign_in_to_account': 'ወደ መለያዎ ይግቡ',
    'sign_in_to_explore_properties': 'መሬት ለማጣራት ይግቡ',
    'not_buyer_account': 'ይህ መለያ የገዢ መለያ አይደለም።',
    'invalid_credentials': 'የተሳሳተ የተጠቃሚ ስም ወይም የይለፍ ቃል',
    'email_or_username': 'ኢሜይል ወይም የተጠቃሚ ስም',
    'remember_me': 'አስታውሰኝ',
    'forgot_password': 'የይለፍ ቃል ረስቷል?',
    'continue_with_google': 'ከGoogle ጋር ቀጥል',
    'dont_have_account': 'እንዲሁ መለያ አለዎት?',
    'already_have_account': 'እንዲሁ መለያ አለዎት?',
    'create_account': 'መለያ ፍጠር',
    'create_seller_account': 'የሻጭ መለያ ፍጠር',
    'create_account_subtitle': 'የንብረት መፈለጊያ ለመጀመር መለያዎን ይፍጠሩ',
    'seller_account_created': 'የሻጭ መለያ በተሳካ ሁኔታ ተፈጠረ! እባኮት ይግቡ.',
    'registration_failed': 'ምዝገባ አልተሳካም',
    'please_fill_required_fields': 'እባክዎ ሁሉንም አስፈላጊ ቦታዎች ይሙሉ',
    'message_sent_success': 'መልዕክት በተሳካ ሁኔታ ተልኳል! በፍጥነት እንደገና እንገናኛለን.',
    'visit_us': 'ብለን ይጎብኙን',
    'call_us': 'ይደውሉን',
    'email_us': 'ኢሜይል ይላኩን',
    'business_hours': 'የንግድ ሰዓቶች',
    'send_us_message': 'ለእኛ መልዕክት ይላኩ',
    'subject': 'ርዕስ',
    'message': 'መልዕክት',
    'about_page_title': 'ስለ ሪል እስቴት ፕሮ',
    'about_page_subtitle': 'በ2015 ጀምሮ ባወቀው የኢትዮጵያ እስቴት ትርጉም እየገናኘ የሚገኘው ቴክኖሎጂ ነው።',
    'our_story': 'ታሪካችን',
    'our_core_values': 'ዋና እሴቶቻችን',
    'our_mission': 'ተልዕኮታችን',
    'our_vision': 'ራዕይአችን',
    'our_mission_text': 'በኢትዮጵያ ውስጥ የእስቴት ግብዓቶችን በግልጽነት፣ በቀላልነት እና በታማኝነት ለማድረግ የሚያስችለን መድረክ መስጠት ነው።',
    'our_vision_text': 'የኢትዮጵያ እስቴት እንቅስቃሴዎችን በቴክኖሎጂ ፣ በሙያ እና በልዩ አገልግሎት ለማስተናገድ የሚችለው ትስስር ለማድረግ ይሆናል።',
    'trust_transparency': 'እምነት እና ግልጽነት',
    'trust_transparency_text': 'በሁሉም ንግዶቻችን ሙሉ ግልጽነትን እናስገባለን እና ደንበኞቻችን ሁሉንም መረጃ ለማግኘት እንረዳቸዋለን።',
    'customer_first': 'ደንበኛ ቀይር',
    'customer_first_text': 'ደንበኞቻችን በእኛ ሁሉም እርምጃ ላይ በማድረግ የተገባውን እና የተስፋ አሳሳብ እናሳያለን።',
    'excellence': 'እርግጠኛነት',
    'excellence_text': 'ከንብረት ዝርዝር እስከ የደንበኛ ድጋፍ ድረስ በሚገኘው ሁሉ ውጤታማ እንሆናለን።',
    'global_standards': 'ዓለም አቀፍ እሴቶች',
    'global_standards_text': 'አካባቢያዊ የኢትዮጵያ ገበያ ሁኔታዎችን በመረዳት ዓለም አቀፍ መለኪያዎችን እንጠብቃለን።',
    'properties_found': '{count} ንብረቶች ያሉበት',
    'property_type_label': 'የንብረት አይነት',
    'all_cities': 'ሁሉም ከተሞች',
    'loading_more': 'እየተጨማረ ነው...',
    'property_not_found': 'ንብረት አልተገኘም',
    'failed_to_load_property': 'ንብረት ማጣሪያ አልተቻለም',
    'contact_property_owner': 'ከባለቤት ጋር ይገናኙ',
    'create_buyer_account': 'የገዢ መለያ ፍጠር',
    'login_to_buyer_account': 'ወደ ገዢ መለያ ይግቡ',
    'please_create_buyer_account': 'እባክዎ ባለ ገዢ መለያ ይፍጠሩ እንዲረጋገጥ ባለቤቱን ያግኙ',
    'amenities_features': 'መገለግራዎች እና ባህሪዎች',
    'open_chat': 'ንግግር እየተከፈተ ነው...',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage === 'am' ? 'am' : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = 'ltr';
  }, [language]);

  const t = useCallback((key) => {
    const translation = translations[language]?.[key] || translations.en[key] || key;
    return translation;
  }, [language]);

  const changeLanguage = useCallback((lang) => {
    if (lang === 'am' || lang === 'en') {
      setLanguage(lang);
      window.location.reload();
    }
  }, []);

  const toggleLanguage = useCallback(() => {
    const newLang = language === 'en' ? 'am' : 'en';
    setLanguage(newLang);
    localStorage.setItem('language', newLang);
    window.location.reload();
  }, [language]);

  const value = {
    language,
    setLanguage,
    changeLanguage,
    toggleLanguage,
    t,
    isAmharic: language === 'am',
    isEnglish: language === 'en',
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageProvider;